NAME "MAIN"
ORG 100H
JMP START

MSG1 DB "PLEASE ENTER DRIVE'S FIRST LETTER TO SCAN : $", 0
MSG2 DB "TOTAL FILE DELETED : $", 0
DTA DB 128 DUP(1)

DIR DB 128 DUP(1)
FILE DB 128 DUP(1); "c:\jony.txt", 0
MAKE DB 128 DUP(1)
CUR DB ".", 0
COUNT DB 0



START:
    ; SET DTA
    MOV AH, 1AH
    MOV DX, OFFSET DTA
    INT 21H

    ; SHOW MESSAGE
    MOV AH, 9
    MOV DX, OFFSET MSG1
    INT 21H

    ;GET DRIVE
    MOV AH, 1
    INT 21H

    ; SET DRIVE NAME
    MOV DI, OFFSET DIR
    MOV [DI], AL
    INC DI
    MOV [DI], ':'
    INC DI
    MOV [DI], '\'
    INC DI
    MOV [DI], 0


    ;PRINT NEW LINE
    MOV AH, 2
    MOV DL, 0DH
    INT 21H
    MOV DL, 0AH
    INT 21H

    ; SEARCH DIRECTORY AND DELETE FILE
    CALL DIRECTORY

    ; PRINT OUTPUT
    MOV AH, 9
    MOV DX, OFFSET MSG2
    INT 21H

    MOV DL, COUNT
    ADD DL, '0'
    MOV AH, 2
    INT 21H

RET
INCLUDE "DIRECTORY.ASM"
